name: Deploy with Github Actions to an instance EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Download project from S3
      run: |
        aws s3 cp s3://my-reallife/mywebapp.zip ./project.zip

    - name: Unzip project
      run: |
        unzip project.zip -d ./project

    - name: Deploy using AWS CodeDeploy
      run: |
        aws deploy create-deployment \
          --application-name production \
          --deployment-group-name mydg \
          --s3-location bucket=my-reallife,key=mywebapp.zip,bundleType=zip

    - name: Check deployment status
      run: |
        DEPLOYMENT_ID=$(aws deploy list-deployments --application-name production --deployment-group-name mydg --query "deployments[0]" --output text)
        aws deploy get-deployment --deployment-id $DEPLOYMENT_ID
