name: Deploy with Github Actions to an instance EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 

    - name: Set up AWS credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::390403859928:role/GitHubActionsOIDCRole
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Set up AWS credentials from Secrets Manager
      uses: aws-actions/aws-secretsmanager-get-secrets@v2
      with:
        secret-ids: my-app-credentials
        parse-json-secrets: true

    - name: Create a zip of the project files
      run: |
        echo "Creating a zip file of the project..."
        zip -r project.zip .

    - name: Delete previous project from S3
      run: |
        echo "Deleting previous project from S3..."
        aws s3 rm s3://my-reallife/mywebapp.zip

    - name: Upload new project to S3
      run: |
        echo "Uploading new project to S3..."
        aws s3 cp project.zip s3://my-reallife/mywebapp.zip

    - name: Deploy using AWS CodeDeploy
      run: |
        aws deploy create-deployment \
          --application-name production \
          --deployment-group-name mydg \
          --s3-location bucket=my-reallife,key=mywebapp.zip,bundleType=zip

    - name: Monitor deployment status
      run: |
        DEPLOYMENT_ID=$(aws deploy list-deployments --application-name production --deployment-group-name mydg --query "deployments[0]" --output text)
        echo "Deployment started with ID: $DEPLOYMENT_ID"
        STATUS="InProgress"
        while [ "$STATUS" == "InProgress" ]; do
          echo "Checking deployment status..."
          RESULT=$(aws deploy get-deployment --deployment-id $DEPLOYMENT_ID)
          STATUS=$(echo $RESULT | jq -r '.deploymentInfo.status')
          echo "Current deployment status: $STATUS"
          if [ "$STATUS" == "Failed" ]; then
            echo "Deployment failed!"
            echo "Details: $RESULT"
            exit 1
          fi
          if [ "$STATUS" == "Succeeded" ]; then
            echo "Deployment succeeded!"
            break
          fi
          sleep 5
        done
